import java.util.Random;

//Welcome to snake and ladder simulator

public class SnakeAndLadder {
     public static void main(String[] args) {
       int playerPosition = 0;
       int noPlay = 1;
       int ladder = 2;
       //int snake = 3;
       
       
       Random random = new Random();
       
       //Roll dice to generate random number between 1 to 6
       int option = random.nextInt(4)+1;
       System.out.println("Condition number is :" + " " + option);
       int dice = random.nextInt(7)+1;
       System.out.println("Random number generated by dice is :" + " " + dice);
       if(option == noPlay){
    	   System.out.println("You got No-Play Option!");
    	   }
       else if(option == ladder){
    	   System.out.println("You got Ladder!");
    	   playerPosition += dice;
    	   }
       else{
    	   System.out.println("You got Snake!");
    	   playerPosition -= dice;
    	   if (playerPosition <= 0){
    		   playerPosition = 0;
    		   }
    	   }
       System.out.println("Curruent position of player is :" + " " + playerPosition);

    }
}